[FIX] mrp: unbuild from partially-done MO
To reproduce the issue:
(enable debug mode)
1. Create three storable products P1, P2
2. Update the available qty of P2: 10
3. Create a BoM:
    - Product: 1 x P1
    - Components: 1 x P2
4. Create and confirm a MO with 10 x P1
5. Produce 6 x P1
6. Post the inventory
7. Cancel the MO
    - It should be mark as done
8. Process an unbuild order based on the MO and for 2 x P1
9. Check the SM of the unbuild order

Error: The quantity is incorrect: 1.2 instead of 2

When generating the moves of the unbuild order, a factor is applied on
the SMs of the MO. However, we use the initial qty of the MO (i.e., 10)
to compute this factor. Therefore, because we want to unbuild 2 x P1,
the factor is equal to `2 / 10 = 0.2`. Then, because we produced 6 x P1,
it gives `6 x 0.2 = 1.2`.

The factor should be based on the actual produced quantity.

OPW-2781308

closes odoo/odoo#92238

Signed-off-by: Tiffany Chang <tic@odoo.com>